### PR TITLE
Create auxiliar file to enable overleaf import ability

### PR DESCRIPTION
**Pull request by LudeeD**
Simple file that if selected as the main file in overleaf will enable the project to be compiled without additional configuration files.
Appears to be the simplest solution

### CODE REVIEW

**Comment by LudeeD** [comment]
Trying to provide an easy way out to #2

**Comment by rj-jesus** [comment]
Maybe I tested this wrong, but it doesn't seem to work... Do not forget to clear Overleaf's cache before changing the main TeX file.

The main problem with the current setup is that overleaf expects the cover to be already produced (i.e. `cover.pdf` to exist). Otherwise, simply setting `matter.tex` as the main file should work.

**Comment by LudeeD** [comment]
My bad :/
It does not work, brain fart xD

**Comment by LudeeD** [comment]
Just my final 2cents to the discussion

Even with cover.pdf present, the output is not the expected... so... I guess my supervisors will have to handle the ugliness of the Dissertation without cover

**Comment by rj-jesus** [comment]
See https://github.com/fabiomaia/ua-thesis-template/issues/2#issuecomment-465199483

**Pull request closed without merging**
